package hotel.entities;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import hotel.credit.CreditCard;
import hotel.utils.IOUtils;

public class Room {
	
	private enum State {READY, OCCUPIED}
	
	int id;
	RoomType roomType;
	List<Booking> bookings;
	State state;

	
	public Room(int id, RoomType roomType) {
		this.id = id;
		this.roomType = roomType;
		bookings = new ArrayList<>();
		state = State.READY;
	}
	

	public String toString() {
		return String.format("Room : %d, %s", id, roomType);
	}


	public int getId() {
		return id;
	}
	
	public String getDescription() {
		return roomType.getDescription();
	}
	
	
	public RoomType getType() {
		return roomType;
	}
	
	public boolean isAvailable(Date arrivalDate, int stayLength) {
		IOUtils.trace("Room: isAvailable");
		for (Booking b : bookings) {
			if (b.doTimesConflict(arrivalDate, stayLength)) {
				return false;
			}
		}
		return true;
	}
	
	
	public boolean isReady() {
		return state == State.READY;
	}

	//Method implemented by Arashdeep kaur
	public Booking book(Guest guest, Date arrivalDate, int stayLength, int numberOfOccupants, CreditCard creditCard)
	{
		Booking booking = new Booking(guest, this, arrivalDate, stayLength, numberOfOccupants, creditCard);
		bookings.add(booking); //insertion of data into dataset
		return booking;	 //returning dataset	
	}

//Code for this method Generated by Arashdeep Kaur
	public void checkin() {
		// Condition to check if room is available or not
		if(state == Room.State.READY){
			state = Room.State.OCCUPIED; //state is occupied
		}
		else
		{
			throw new RuntimeException("Room state is already occupied!"); //show a runtime error message if the room state is already in occupied state.
		}
	}

	// metod generated by Arashdeep kaur
	public void checkout(Booking booking) 
	{
		//condition to check weather room is vacant or occupied
		if (state != State.OCCUPIED) {
			String mesg = String.format("Room: checkout : bad state : %s", new Object[] { state });
			throw new RuntimeException(mesg);
		}
		bookings.remove(booking); //empty dataset
		state = State.READY; //set room state to ready
	}


}
